# render.yaml
services:
  - type: web
    name: biblioteca-app
    env: python
    # AÑADE LOS COMANDOS AQUI:
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn Biblioteca.wsgi:application
    # LA SECCIÓN preDeployCommand YA NO DEBE ESTAR AQUÍ
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      # ... tus otras variables de entorno como DATABASE_URL, ALLOWED_HOSTS, etc.