# render.yaml
services:
  - type: web
    name: BibliotecaDeLibros
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn Biblioteca.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      # ¡IMPORTANTE! Actualiza esta URL con la URL del nuevo servicio de Render que crearás
      - key: ALLOWED_HOSTS
        value: "https://biblioteca-app-nueva-tu_id.onrender.com/" # EJEMPLO: CAMBIA ESTO