# render.yaml
services:
  - type: web
    name: biblioteca-app
    env: python
    # Nueva sintaxis para buildCommand: todo en una línea con '&&'
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --noinput
    startCommand: gunicorn Biblioteca.wsgi:application
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "https://biblioteca-app-i0l8.onrender.com/"