# Generated by Django 4.0.7 on 2024-11-22 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LibrosBachillerato',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='bachillerato/images/')),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='bachillerato/docs/')),
            ],
        ),
        migrations.CreateModel(
            name='LibrosBasica',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='basica/images/')),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='basica/docs/')),
            ],
        ),
        migrations.CreateModel(
            name='LibrosInicial',
            fields=[
                ('id_libro', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('autor', models.CharField(max_length=255)),
                ('fecha_publicacion', models.DateField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='inicial/images/')),
                ('categoria', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('documento', models.FileField(blank=True, null=True, upload_to='inicial/docs/')),
            ],
        ),
    ]
